spring.application.name=CalendarioDP

# Configuración de la conexión a la base de datos PostgreSQL con R2DBC
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/calendariodp
spring.r2dbc.username=postgres
spring.r2dbc.password=0000

jwt.secret=tu_secreto_super_seguro
jwt.issuer=CalendarioDP
jwt.expiration=3600000